### ISSUE TITLE
Validation error: variable arr has not been declared

### ISSUE THREAD

**Issue by MarioLocati** [ec-jrc/datacite-to-dcat-ap#4]
When trying to validate "datacite-to-dcat-ap.xsl" using Oxygen XML Editor, I get an error about "variable arr has not been declared"

https://github.com/ec-jrc/datacite-to-dcat-ap/blob/5e99eda7f5425345189d53a4aba78b43ea501cbd/datacite-to-dcat-ap.xsl#L778

**Comment by andrea-perego** [comment]
Thanks for reporting this bug, @MarioLocati .

It should now be fixed via commit https://github.com/ec-jrc/datacite-to-dcat-ap/commit/accea3443744dd6d950b8a0a3ffb9db945656ba1 , although I have not tested it with Oxygen.

It you find any other issue, please let me know.

**Comment by MarioLocati** [comment]
@andrea-perego Cheers, that solve it!
